[project]
name = "app"
version = "0.1.0"
dependencies = [ "fastapi==0.121.0", "python-dotenv==1.2.1", "python-multipart==0.0.21", "requests==2.32.5", "httpx==0.28.1", "pydantic==2.12.4", "openai==2.15.0", "pypdf2==3.0.1", "beautifulsoup4>=4.12", "python-docx==1.2.0", "svix==1.84.1", "lxml==6.0.2", "sqlalchemy[asyncio]>=2.0", "psycopg[binary]==3.3.4", "sentry-sdk[fastapi]>=2.0", "vercel==0.7.1" ]
requires-python = "~=3.12.0"
