/**
 * RoundThreeForm - Section 3: Content Spine (Two-Phase)
 * Phase 1: User writes their Point of View (the claim the video will defend)
 * Phase 2: AI generates argument structure → user reviews/edits
 */

import { useState } from "react";
import FieldCard from "./FieldCard";
import type { BriefField } from "../types";
import { KNOWLEDGE_SHARE_REQUIRED_FIELDS, areRequiredFieldsFilled } from "../types";
import { cn } from "@/lib/utils";
import { Info, Loader2 } from "lucide-react";

interface BriefContext {
  audience: string;
  topic: string;
  goal: string;
}

interface RoundThreeFormProps {
  fields: Record<string, BriefField>;
  onFieldChange: (key: string, value: string | string[] | boolean) => void;
  onFieldConfirm: (key: string) => void;
  onFieldUnconfirm?: (key: string) => void;
  onSectionConfirm: () => void;
  onGenerateContentSpine?: (pov: string, feedback?: string) => Promise<void>;
  briefContext?: BriefContext;
  disabled?: boolean;
  researchComplete?: boolean;
  showConfirmButton?: boolean;
}

const GENERATED_FIELDS = [
  "core_talking_points",
  "misconceptions",
  // "must_avoid", // Hidden from UI — still generated by backend and consumed by Director
];

function PovTooltip() {
  const [open, setOpen] = useState(false);

  return (
    <div className="relative inline-block">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        onMouseEnter={() => setOpen(true)}
        onMouseLeave={() => setOpen(false)}
        className="text-muted-foreground hover:text-foreground transition-colors"
        aria-label="What is a point of view?"
      >
        <Info className="w-4 h-4" />
      </button>
      {open && (
        <div className="absolute left-0 top-6 z-50 w-[380px] bg-white border border-border rounded-lg shadow-lg p-4 text-sm space-y-3">
          <div>
            <p className="font-medium text-foreground mb-1">Weak vs. stronger</p>
            <div className="space-y-2 text-muted-foreground">
              <div>
                <p><span className="text-[#A63228] font-medium">Weak:</span> &quot;AI can help marketers work faster.&quot;</p>
                <p><span className="text-[#3A6B47] font-medium">Stronger:</span> &quot;For product marketers, AI is not most valuable for writing copy faster; it is most valuable for turning scattered inputs into sharper strategic angles.&quot;</p>
              </div>
              <div>
                <p><span className="text-[#A63228] font-medium">Weak:</span> &quot;Startup exits are hard.&quot;</p>
                <p><span className="text-[#3A6B47] font-medium">Stronger:</span> &quot;For first-time founders, startup exits are not mainly about finding a buyer; they are about surviving the 18-month dead zone when neither growth nor M&A interest is strong enough.&quot;</p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default function RoundThreeForm({
  fields,
  onFieldChange,
  onFieldConfirm,
  onFieldUnconfirm,
  onSectionConfirm,
  onGenerateContentSpine,
  briefContext,
  disabled = false,
  researchComplete: _researchComplete = true,
  showConfirmButton = true,
}: RoundThreeFormProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [showRegenerate, setShowRegenerate] = useState(false);
  const [regenerateFeedback, setRegenerateFeedback] = useState("");

  // Determine phase: if generated fields have values, we're in Phase 2
  const hasGeneratedFields = GENERATED_FIELDS.some(
    (key) => {
      const val = fields[key]?.value;
      return Array.isArray(val) ? val.length > 0 : Boolean(val);
    }
  );
  const phase: "pov" | "spine" = hasGeneratedFields ? "spine" : "pov";

  const povValue = typeof fields.point_of_view?.value === "string" ? fields.point_of_view.value : "";

  const handleGenerate = async (feedback?: string) => {
    if (!onGenerateContentSpine || !povValue.trim()) return;
    setIsGenerating(true);
    setGenerateError(null);
    try {
      await onGenerateContentSpine(povValue.trim(), feedback);
      setShowRegenerate(false);
      setRegenerateFeedback("");
    } catch (err) {
      setGenerateError(err instanceof Error ? err.message : "Failed to generate content spine");
    } finally {
      setIsGenerating(false);
    }
  };

  const requiredFields = KNOWLEDGE_SHARE_REQUIRED_FIELDS[3];
  const canConfirm = phase === "spine" && areRequiredFieldsFilled(fields, 3);

  return (
    <div className="space-y-6">
      {/* Section Header */}
      <div style={{ marginBottom: "22px" }}>
        <h2
          style={{
            fontFamily: "'Fraunces', serif",
            fontSize: "28px",
            fontWeight: 400,
            color: "#1C2118",
            letterSpacing: "-0.6px",
            lineHeight: "1.15",
            marginBottom: "5px",
          }}
        >
          Section 3: Content Spine & Key Point of View
        </h2>
        <p style={{ fontSize: "13.5px", fontWeight: 300, color: "#5A6352" }}>
          Your point of view is the single claim this video will build and defend.
          Teaching a concept? Your PoV keeps it from becoming an assembly of facts.
          Teaching a tool? Your PoV is your way of using it — not a tour of features.
        </p>
      </div>

      {/* Context Reminder */}
      {briefContext && phase === "pov" && (
        <div className="flex gap-4 text-xs text-muted-foreground bg-muted/30 rounded-md px-3 py-2">
          <span className="font-medium text-foreground">Reminder:</span>
          {briefContext.audience && (
            <span><span className="font-medium text-foreground">For:</span> {briefContext.audience}</span>
          )}
          {briefContext.topic && (
            <span><span className="font-medium text-foreground">Topic:</span> {briefContext.topic}</span>
          )}
          {briefContext.goal && (
            <span><span className="font-medium text-foreground">Goal:</span> {briefContext.goal}</span>
          )}
        </div>
      )}

      {/* POV Input — always visible */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <label
            className="text-sm font-medium text-foreground"
            htmlFor="pov-input"
          >
            Your point of view <span className="text-[#A63228]">*</span>
          </label>
          <PovTooltip />
        </div>
        <textarea
          id="pov-input"
          value={povValue}
          onChange={(e) => onFieldChange("point_of_view", e.target.value)}
          disabled={disabled || isGenerating || (phase === "spine" && !generateError)}
          placeholder="e.g. For product marketers, AI is not most valuable for writing copy faster; it is most valuable for turning scattered inputs into sharper strategic angles."
          className={cn(
            "w-full rounded-lg border border-border bg-white px-3 py-2.5 text-sm min-h-[80px] resize-y",
            "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary",
            "disabled:opacity-60 disabled:cursor-not-allowed",
            "placeholder:text-muted-foreground/50"
          )}
          rows={3}
        />
      </div>

      {/* Generate Error */}
      {generateError && (
        <div className="flex items-center gap-2 bg-[#FBEAE8] border border-[#E8C0BC] text-[#A63228] rounded-lg px-3 py-2 text-xs">
          {generateError}
        </div>
      )}

      {/* Phase 1: Generate button */}
      {phase === "pov" && showConfirmButton && (
        <div className="border-t pt-4">
          <button
            onClick={() => handleGenerate()}
            disabled={!povValue.trim() || disabled || isGenerating}
            className={cn(
              "w-full py-3 px-4 rounded-lg font-medium transition-colors flex items-center justify-center gap-2",
              povValue.trim() && !disabled && !isGenerating
                ? "bg-primary text-primary-foreground hover:bg-primary/90"
                : "bg-muted text-muted-foreground cursor-not-allowed"
            )}
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Generating content spine...
              </>
            ) : (
              "Generate Content Spine \u2192"
            )}
          </button>
        </div>
      )}

      {/* Phase 2: Generated field cards */}
      {phase === "spine" && (
        <div className="space-y-4">
          <div className="border-t pt-4">
            <p className="text-xs text-muted-foreground mb-3">
              Generated from your point of view. Edit any field before confirming.
            </p>
          </div>
          {GENERATED_FIELDS.map((key) => {
            const field = fields[key];
            if (!field) return null;
            return (
              <FieldCard
                key={key}
                fieldKey={key}
                field={field}
                isRequired={requiredFields.includes(key)}
                onChange={(value) => onFieldChange(key, value)}
                onConfirm={() => onFieldConfirm(key)}
                onUnconfirm={
                  onFieldUnconfirm ? () => onFieldUnconfirm(key) : undefined
                }
                disabled={disabled}
              />
            );
          })}
        </div>
      )}

      {/* Phase 2: Regenerate */}
      {phase === "spine" && onGenerateContentSpine && (
        <div className="border-t pt-4">
          {!showRegenerate ? (
            <button
              type="button"
              onClick={() => setShowRegenerate(true)}
              disabled={disabled || isGenerating}
              className="text-xs text-muted-foreground hover:text-foreground transition-colors underline underline-offset-2"
            >
              Not quite right? Regenerate with feedback
            </button>
          ) : (
            <div className="space-y-2">
              <textarea
                value={regenerateFeedback}
                onChange={(e) => setRegenerateFeedback(e.target.value)}
                placeholder="e.g. Make the talking points more focused on the counterintuitive insight, less on features"
                className={cn(
                  "w-full rounded-lg border border-border bg-white px-3 py-2.5 text-sm min-h-[60px] resize-y",
                  "focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary",
                  "placeholder:text-muted-foreground/50"
                )}
                rows={2}
              />
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={() => handleGenerate(regenerateFeedback || undefined)}
                  disabled={isGenerating}
                  className={cn(
                    "flex-1 py-2 px-3 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-2",
                    !isGenerating
                      ? "bg-primary text-primary-foreground hover:bg-primary/90"
                      : "bg-muted text-muted-foreground cursor-not-allowed"
                  )}
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      Regenerating...
                    </>
                  ) : (
                    "Regenerate Content Spine \u2192"
                  )}
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setShowRegenerate(false);
                    setRegenerateFeedback("");
                  }}
                  disabled={isGenerating}
                  className="py-2 px-3 rounded-lg text-sm text-muted-foreground hover:text-foreground transition-colors"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Phase 2: Confirm button */}
      {phase === "spine" && showConfirmButton && (
        <div className="border-t pt-4">
          <button
            onClick={onSectionConfirm}
            disabled={!canConfirm || disabled}
            className={cn(
              "w-full py-3 px-4 rounded-lg font-medium transition-colors",
              canConfirm && !disabled
                ? "bg-primary text-primary-foreground hover:bg-primary/90"
                : "bg-muted text-muted-foreground cursor-not-allowed"
            )}
          >
            {canConfirm
              ? "Confirm Section 3 \u2192"
              : "Fill all required fields to continue"}
          </button>
        </div>
      )}
    </div>
  );
}
